<a href="https://colab.research.google.com/github/Adhoc123/Deep-Learning-for-Computer-Vision/blob/main/Tensorflow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%autosave 60

Autosaving every 60 seconds


In [ ]:
import tensorflow as tf
import numpy as np


In [ ]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string = tf.constant(['hey','self','lion'])
print(tensor_string)

tf.Tensor([b'hey' b'self' b'lion'], shape=(3,), dtype=string)


In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0,-3,4,42], dtype=tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  4. 42.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [ ]:
tensor_two_d = tf.constant([
    [3,4,-4],
    [1,2,6],
    [0,3,1],
    [6,5,2]
])
print(tensor_two_d)

tf.Tensor(
[[ 3  4 -4]
 [ 1  2  6]
 [ 0  3  1]
 [ 6  5  2]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
  [[3,4,2],
  [3,3,2]],
  [[32,3,4],
  [0,9,2]],
  [[4,3,1],
  [-2,-2,9]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 3  4  2]
  [ 3  3  2]]

 [[32  3  4]
  [ 0  9  2]]

 [[ 4  3  1]
  [-2 -2  9]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
print(tensor_zero_d.ndim)
print(tensor_one_d.ndim)
print(tensor_two_d.ndim)
print(tensor_three_d.ndim)

0
1
2
3


In [ ]:
tensor_four_d = tf.constant([
[
  [[3,4,2],
  [3,3,2]]
],
[
  [[3,4,2],
  [3,3,2]]

]
])

print(tensor_four_d)

tf.Tensor(
[[[[3 4 2]
   [3 3 2]]]


 [[[3 4 2]
   [3 3 2]]]], shape=(2, 1, 2, 3), dtype=int32)


In [ ]:
print(tensor_four_d.ndim)

4


In [ ]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=5,
    batch_shape=[3,4],
    dtype=tf.dtypes.bool,
    name=None
)

In [ ]:
eye_tensor

<tf.Tensor: shape=(3, 4, 5, 5), dtype=bool, numpy=
array([[[[ True, False, False, False, False],
         [False,  True, False, False, False],
         [False, False,  True, False, False],
         [False, False, False,  True, False],
         [False, False, False, False,  True]],

        [[ True, False, False, False, False],
         [False,  True, False, False, False],
         [False, False,  True, False, False],
         [False, False, False,  True, False],
         [False, False, False, False,  True]],

        [[ True, False, False, False, False],
         [False,  True, False, False, False],
         [False, False,  True, False, False],
         [False, False, False,  True, False],
         [False, False, False, False,  True]],

        [[ True, False, False, False, False],
         [False,  True, False, False, False],
         [False, False,  True, False, False],
         [False, False, False,  True, False],
         [False, False, False, False,  True]]],


       [[[ True, Fa

In [ ]:
fill_tensor = tf.fill(
    [1,3,2], 4, name=None, layout=None
)
print(fill_tensor)

tf.Tensor(
[[[4 4]
  [4 4]
  [4 4]]], shape=(1, 3, 2), dtype=int32)


In [ ]:
ones_tensor = tf.ones(
    [4,2,3],
    dtype=tf.dtypes.int32,
    name=None,
    layout=None

)
print(ones_tensor)

tf.Tensor(
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1]
  [1 1]
  [1 1]]], shape=(1, 3, 2), dtype=int32)


In [ ]:
zeros_tensor = tf.zeros(
    [4,2,3],
    dtype=tf.dtypes.int32,
    name=None,
    layout=None

)
print(zeros_tensor)

tf.Tensor(
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
tf.shape(eye_tensor)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 5, 5], dtype=int32)>

In [ ]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[1, 1, 1], [2, 2, 2]])
tf.rank(t)  # 3

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
t = tf.constant([[1, 1, 1], [2, 2, 2]])
tf.size(t, out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [ ]:
random_tensor = tf.random.normal(
    [3,4],
    mean=50.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[49.89209  51.509872 49.193043 47.722195]
 [51.16762  51.193386 50.396503 49.704536]
 [50.87161  50.25228  49.515114 49.678463]], shape=(3, 4), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    [3,4],
    minval=3,
    maxval=5,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[4 3 3 4]
 [4 3 3 4]
 [3 3 4 4]], shape=(3, 4), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))




tf.Tensor([2 0 1], shape=(3,), dtype=int32)
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
tf.Tensor([0 1 1], shape=(3,), dtype=int32)
tf.Tensor([2 1 2], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))


tf.Tensor([2 0 1], shape=(3,), dtype=int32)
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
tf.Tensor([0 1 1], shape=(3,), dtype=int32)
tf.Tensor([2 1 2], shape=(3,), dtype=int32)


In [ ]:
tensor_indexed = tf.constant([3,4,5,3,3,3])
print(tensor_indexed[0:4])
print(tensor_indexed[:-3])

tf.Tensor([3 4 5 3], shape=(4,), dtype=int32)
tf.Tensor([3 4 5], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [43,5,3],
    [1,2,3],
    [3,43,4]
])
print(tensor_two_d[0:2,:])

tf.Tensor(
[[43  5  3]
 [ 1  2  3]], shape=(2, 3), dtype=int32)


In [ ]:
tf.range(2,10)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tensor_three_d = tf.constant([
  [ [3,4,2],[3,3,2] ], [ [32,3,4],[0,9,2] ], [ [4,3,1],[-2,-2,9] ]
])
print(tensor_three_d[0:2,:2,:1])

tf.Tensor(
[[[ 3]
  [ 3]]

 [[32]
  [ 0]]], shape=(2, 2, 1), dtype=int32)
