<a href="https://colab.research.google.com/github/Adhoc123/Deep-Learning-for-Computer-Vision/blob/main/Tensorflow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%autosave 60

Autosaving every 60 seconds


In [ ]:
import tensorflow as tf
import numpy as np


In [ ]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string = tf.constant(['hey','self','lion'])
print(tensor_string)

tf.Tensor([b'hey' b'self' b'lion'], shape=(3,), dtype=string)


In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0,-3,4,42], dtype=tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  4. 42.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [ ]:
tensor_two_d = tf.constant([
    [3,4,-4],
    [1,2,6],
    [0,3,1],
    [6,5,2]
])
print(tensor_two_d)

tf.Tensor(
[[ 3  4 -4]
 [ 1  2  6]
 [ 0  3  1]
 [ 6  5  2]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
  [[3,4,2],
  [3,3,2]],
  [[32,3,4],
  [0,9,2]],
  [[4,3,1],
  [-2,-2,9]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 3  4  2]
  [ 3  3  2]]

 [[32  3  4]
  [ 0  9  2]]

 [[ 4  3  1]
  [-2 -2  9]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
print(tensor_zero_d.ndim)
print(tensor_one_d.ndim)
print(tensor_two_d.ndim)
print(tensor_three_d.ndim)

0
1
2
3


In [ ]:
tensor_four_d = tf.constant([
[
  [[3,4,2],
  [3,3,2]]
],
[
  [[3,4,2],
  [3,3,2]]

]
])

print(tensor_four_d)

tf.Tensor(
[[[[3 4 2]
   [3 3 2]]]


 [[[3 4 2]
   [3 3 2]]]], shape=(2, 1, 2, 3), dtype=int32)


In [ ]:
print(tensor_four_d.ndim)

4


In [ ]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [49]:
eye_tensor = tf.eye(
    num_rows=6,
    num_columns=7,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)

In [51]:
eye_tensor

<tf.Tensor: shape=(6, 7), dtype=bool, numpy=
array([[ True, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False],
       [False, False,  True, False, False, False, False],
       [False, False, False,  True, False, False, False],
       [False, False, False, False,  True, False, False],
       [False, False, False, False, False,  True, False]])>