<a href="https://colab.research.google.com/github/Adhoc123/Deep-Learning-for-Computer-Vision/blob/main/Tensorflow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%autosave 60

Autosaving every 60 seconds


In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0,-3,4,0.2])
print(tensor_one_d)

tf.Tensor([ 2.   0.  -3.   4.   0.2], shape=(5,), dtype=float32)


In [ ]:
tensor_two_d = tf.constant([
    [3,4,-4],
    [1,2,6],
    [0,3,1],
    [6,5,2]
])
print(tensor_two_d)

tf.Tensor(
[[ 3  4 -4]
 [ 1  2  6]
 [ 0  3  1]
 [ 6  5  2]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
  [[3,4,2],
  [3,3,2]],
  [[32,3,4],
  [0,9,2]],
  [[4,3,1],
  [-2,-2,9]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 3  4  2]
  [ 3  3  2]]

 [[32  3  4]
  [ 0  9  2]]

 [[ 4  3  1]
  [-2 -2  9]]], shape=(3, 2, 3), dtype=int32)
